### ISSUE TITLE
NullPointerException: Cannot invoke "org.apache.avro.Schema$Field.schema()" because "field" is null

### ISSUE THREAD

**Issue by UjavalMehta** [corunet/kloadgen#156]
Getting below Error:
2022-01-13 08:12:49,752 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
java.lang.NullPointerException: Cannot invoke "org.apache.avro.Schema$Field.schema()" because "field" is null
at net.coru.kloadgen.processor.AvroSchemaProcessor.extractConstraints(AvroSchemaProcessor.java:124) ~[kloadgen-3.6.2-kloadgen-p
lugin-3.6.2.jar:?]
at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:110) ~[kloadgen-3.6.2-kloadgen-plugin-3.6.2.ja
r:?]
at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:60) ~[kloadgen-3.6.2-kloadgen-plugin-3.6
.2.jar:?]
at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:137) ~[kloadgen-3.6.2-kloadgen-plugin-3.6.2.jar
:?]
at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.1]
at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.1]
at java.lang.Thread.run(Thread.java:833) [?:?]

I am using below attached Schema :
[ProcessedMessage.txt](https://github.com/corunet/kloadgen/files/7861049/ProcessedMessage.txt)

Below PepperBox values is working fine for the same Schema:
[ProcessedMessage_PepperBox_Values.txt](https://github.com/corunet/kloadgen/files/7861056/ProcessedMessage_PepperBox_Values.txt)

From kloadGen Perspective:
![image](https://user-images.githubusercontent.com/91044482/149291993-a387dc17-0d76-4595-a1d9-61599673c5a2.png)
![image](https://user-images.githubusercontent.com/91044482/149292064-73cb45ba-98fc-46a1-8933-476b378b78fa.png)
![image](https://user-images.githubusercontent.com/91044482/149292131-a9024770-0289-48a6-b507-282ecf40d4ce.png)
![image](https://user-images.githubusercontent.com/91044482/149292174-c858879a-41a1-4449-9742-f9e515895845.png)

I am using 3.6.2 version and uploaded schema manually on "Value Schema File Load Generator Config"
Please help on error.
Please let me know If you need more information

**Comment by Rivarsal** [comment]
This error usually happens because:

 1. Your Schema doesn´t have the same name as the FieldValueMapping (Have you changed the name?) so it doesn´t find the right field.
 2. Your Schema doesn´t have that field at all and can´t find it. (Have you deleted the name?)

I ran tests with your Avro Schema and it worked just fine. 

Also, there is a couple of things I must say: 

1. Your function ${__time()} will fail in the timestamp field since it doesn´t generate that type of value.
2. Your null value in headers.providerMessageTimeStamp will fail. This is on us, because we don´t support null values in the FieldValueList. If you want a null value, you have to take it out of the Avro File for now.
 
We will develop a null value support since we believe it´s important.

Sorry for the troubles!

**Comment by UjavalMehta** [comment]
Thank You Rivarsal for quick response
I have not changed/deleted any name from schema point of view.
${__time()} is working for other events and I believe that should not be issue
For header.providerMessageTimeStamp and other null values, Earlier I have set as "[]" but then I have added "[null]" values but it still having the same issue

I will pull schema from environment again and will double check whether there is any change in schema or not

**Comment by UjavalMehta** [comment]
Sorry for the confusion
Environment schema got changed and gain that error
Its passing for me now
But yes, "null" value is important. Once you have that addon, please update 
Thank you for your time
