### ISSUE TITLE
Unable to run the kafka poducer

### ISSUE THREAD

**Issue by sushmatshetty** [corunet/kloadgen#189]
Error while processing sampler: 'Kafka Producer'.
java.lang.NullPointerException: Cannot invoke "org.apache.avro.Schema$Field.schema()" because "field" is null
	at net.coru.kloadgen.processor.AvroSchemaProcessor.isOptionalField(AvroSchemaProcessor.java:261) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:97) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:60) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:137) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by cmunozgomez** [comment]
Hi @sushmatshetty,

Are there any news about this? If it isn't, I will close this issue in the next days.

If you have problems later on, please feel free to open a new issue and we will try to help you.

Cheers!

**Comment by sushmatshetty** [comment]
Will get back if I have problems.thanks
