### ISSUE TITLE
[Repo: protobuf-import-test-support]: 

### ISSUE THREAD

**Issue by nrellanti** [corunet/kloadgen#204]
### What happened?

import "google/protobuf/timestamp.proto"; 
import "google/protobuf/wrappers.proto";

Getting below errors: (proto file attached)

2022-03-30 10:49:18,755 ERROR n.c.k.l.i.ProtobufLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other
com.google.protobuf.Descriptors$DescriptorValidationException: google.protobuf.DoubleValue.value: "value" is already defined in "google.protobuf.DoubleValue".

2022-03-30 10:49:18,757 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
net.coru.kloadgen.exception.KLoadGenException: com.google.protobuf.Descriptors$DescriptorValidationException: google.protobuf.DoubleValue.value: "value" is already defined in "google.protobuf.DoubleValue".
	at net.coru.kloadgen.loadgen.impl.ProtobufLoadGenerator.setUpGenerator(ProtobufLoadGenerator.java:43) ~
[enriched_positions.zip](https://github.com/corunet/kloadgen/files/8382094/enriched_positions.zip)

### KloadGen Version

Kloadgen-4.0.0

### Relevant log output

```shell
2022-03-30 11:13:16,523 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2022-03-30 11:13:16,524 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2022-03-30 11:13:16,529 INFO o.a.j.p.j.s.JavaSampler: Created class: net.coru.kloadgen.sampler.KafkaSchemaSampler. Uses tearDownTest: 
2022-03-30 11:13:16,530 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2022-03-30 11:13:16,538 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2022-03-30 11:13:16,539 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2022-03-30 11:13:16,539 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2022-03-30 11:13:16,539 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2022-03-30 11:13:16,541 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2022-03-30 11:13:16,541 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2022-03-30 11:13:16,543 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2022-03-30 11:13:16,809 ERROR n.c.k.l.i.ProtobufLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other
io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'abc.Ping' not found.; error code: 40401
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:297) ~[kloadgen-4.0.0-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:367) ~[kloadgen-4.0.0-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:893) ~[kloadgen-4.0.0-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:884) ~[kloadgen-4.0.0-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:469) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.AbstractLoadGenerator.retrieveSchema(AbstractLoadGenerator.java:24) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.ProtobufLoadGenerator.setUpGenerator(ProtobufLoadGenerator.java:28) [kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:411) [kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:84) [kloadgen-4.0.0-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2022-03-30 11:13:16,812 ERROR n.c.k.l.i.ProtobufLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other
com.google.protobuf.Descriptors$DescriptorValidationException: google.protobuf.Timestamp.value: "value" is already defined in "google.protobuf.Timestamp".
	at com.google.protobuf.Descriptors$DescriptorPool.addSymbol(Descriptors.java:2496) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:1452) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:991) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:899) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:629) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FileDescriptor.<init>(Descriptors.java:538) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:311) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:282) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema.init(DynamicSchema.java:241) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:203) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:42) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema$Builder.build(DynamicSchema.java:298) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.processor.ProtoBufProcessorHelper.processImported(ProtoBufProcessorHelper.java:152) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.processor.ProtoBufProcessorHelper.buildDescriptor(ProtoBufProcessorHelper.java:38) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.processor.ProtobufSchemaProcessor.processSchema(ProtobufSchemaProcessor.java:60) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.ProtobufLoadGenerator.setUpGenerator(ProtobufLoadGenerator.java:40) [kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:417) [kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:84) [kloadgen-4.0.0-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2022-03-30 11:13:16,812 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
net.coru.kloadgen.exception.KLoadGenException: com.google.protobuf.Descriptors$DescriptorValidationException: google.protobuf.Timestamp.value: "value" is already defined in "google.protobuf.Timestamp".
	at net.coru.kloadgen.loadgen.impl.ProtobufLoadGenerator.setUpGenerator(ProtobufLoadGenerator.java:43) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:417) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:84) ~[kloadgen-4.0.0-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.protobuf.Descriptors$DescriptorValidationException: google.protobuf.Timestamp.value: "value" is already defined in "google.protobuf.Timestamp".
	at com.google.protobuf.Descriptors$DescriptorPool.addSymbol(Descriptors.java:2496) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:1452) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FieldDescriptor.<init>(Descriptors.java:991) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:899) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$Descriptor.<init>(Descriptors.java:629) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FileDescriptor.<init>(Descriptors.java:538) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:311) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.google.protobuf.Descriptors$FileDescriptor.buildFrom(Descriptors.java:282) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema.init(DynamicSchema.java:241) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:203) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema.<init>(DynamicSchema.java:42) ~[kloadgen-4.0.0-plugin.jar:?]
	at com.github.os72.protobuf.dynamic.DynamicSchema$Builder.build(DynamicSchema.java:298) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.processor.ProtoBufProcessorHelper.processImported(ProtoBufProcessorHelper.java:152) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.processor.ProtoBufProcessorHelper.buildDescriptor(ProtoBufProcessorHelper.java:38) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.processor.ProtobufSchemaProcessor.processSchema(ProtobufSchemaProcessor.java:60) ~[kloadgen-4.0.0-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.ProtobufLoadGenerator.setUpGenerator(ProtobufLoadGenerator.java:40) ~[kloadgen-4.0.0-plugin.jar:?]
	... 8 more
2022-03-30 11:13:16,812 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2022-03-30 11:13:16,813 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2022-03-30 11:13:16,813 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2022-03-30 11:13:16,813 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by jemacineiras** [comment]
Hi @nrellanti,

I'll take a look at it.

Cheers!

**Comment by jemacineiras** [comment]
Hi @nrellanti,
I have a fix ready to merge, if you don't mind testing it.
Just comment a couple of things.

- We release version 4.0.0 last week, so now protobuff support is already in master.
- We have changed the installation procedure, because now we are using Maven Central for delivery, the jar name had changed. From now is kloadgen-<version number>.jar

Cheers

**Comment by nrellanti** [comment]
@jemacineiras , I will test and update the status. 
Thank you

**Comment by nrellanti** [comment]
> @jemacineiras , I will test and update the status. Thank you

So I will test on Master Branch, if it is different , please let me know.

**Comment by jemacineiras** [comment]
hi @nrellanti,

That is the branch where I'm working to solve your issue.
I will wait for your feedback.
Thanks!

**Comment by nrellanti** [comment]
Hi @jemacineiras,
Tested and verified the fix, it was working as expected. Thank you !
