### ISSUE TITLE
[Issue]: FieldValueList with a single item is treated as sequence which breaks for non-numeric field value lists

### ISSUE THREAD

**Issue by t-h-e** [corunet/kloadgen#235]
### What happened?

I have the following field value mapping:
```
data[${amount}].stringFieldValueList | seq | 0 | [${stringFieldValueList}]
```
where `data[].stringFieldValueList` is really a string, but to use field value list, it has to be defined as `seq`.

`${stringFieldValueList}` is read from a CSV filed an may vary in length. The length of `${stringFieldValueList}` defines the number `${amount}`. This works well as long as `${stringFieldValueList}` has more than one value.

In case `${stringFieldValueList}` has a single value, `data[${amount}].stringFieldValueList` is treated as sequence rather than as field value list and `RandomObject#generateSeq` rather than `RandomObject#generateSequenceForFieldValueList` is called. Calling `RandomObject#generateSeq` a single time with a field that is actually a `string` works, as `getFirstValueOrDefaultForType` is called. The second time `addOneCasted` is called, which does not work for `string`, see log.

The following test plan demonstrates the problem by alternating sending a message where `${amount}` is one then two, and ${stringFieldValueList} set to one and two values.

[FieldValueListBug.jmx.txt](https://github.com/corunet/kloadgen/files/8581238/FieldValueListBug.jmx.txt)
[FieldValueListBug.avsc.txt](https://github.com/corunet/kloadgen/files/8581244/FieldValueListBug.avsc.txt)
(with .txt extension as jmx and avsc are not supported)

### KloadGen Version

4.0.8

### Relevant log output

```shell
2022-04-28 10:58:44,789 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request KafkaSchemaSampler'.
java.lang.NumberFormatException: Character O is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
	at java.math.BigDecimal.<init>(BigDecimal.java:518) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:401) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:834) ~[?:?]
	at net.coru.kloadgen.randomtool.random.RandomObject.addOneCasted(RandomObject.java:209) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.randomtool.random.RandomObject.lambda$generateSeq$0(RandomObject.java:44) ~[kloadgen-4.0.8.jar:?]
	at java.util.HashMap.compute(HashMap.java:1228) ~[?:?]
	at net.coru.kloadgen.randomtool.random.RandomObject.generateSeq(RandomObject.java:41) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.randomtool.generator.AvroGeneratorTool.generateObject(AvroGeneratorTool.java:69) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObject(AvroSchemaProcessor.java:379) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObjectArray(AvroSchemaProcessor.java:437) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.processFieldValueMappingAsRecordArray(AvroSchemaProcessor.java:184) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:140) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:51) ~[kloadgen-4.0.8.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:151) ~[kloadgen-4.0.8.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by cmunozgomez** [comment]
Hi @t-h-e 

Thank you for your collaboration, we will review the changes you propose and we will inform you of anything that we see that should be changed.

If everything is correct, proceed to merge the pull request that you have opened.

**Comment by t-h-e** [comment]
Hi @cmunozgomez ,

I think the current PR fixes the issue described above. But while testing the PR I noticed another bug in the `seq` implementation in combination with JMeter variables.

Assume we have the following field value mapping:
```
data[${amount}].intFieldValueList | seq | 0 | [${intFieldValueList}]
```
Note that is now int rather than string.

Lets assume we have a loop around the KafkaSchemaSampler as in the example attached to this issue.
The following table represents three iterations (each row is one iteration), and shows the values of the variables and the output.
| ${intFieldValueList} | ${amount} | output |
|--|--|--|
| 1 | 1 | {"data": [ { "intFieldValueList": 1 } ] } |
| 5,6 | 2 | {"data": [ { "intFieldValueList": 5 }, { "intFieldValueList": 6 } ] } |
| 9 | 1 | {"data": [ { "intFieldValueList": 2 } ] } |

The issue is the following.
- In the first iteration, `intFieldValueList` is treated as sequence with the start value `1` which results in output `1`
- In the second iteration `intFieldValueList ` is treated as field value list and the sequence values do not matter. The output is `5` and `6` as the field value list specifies two values that are used.
- In the third iteration, the problem occurs as the field value list contains only a single value and therefore is treated as sequence again. As the previous values was `1`, the next is `2`, even though `9` was specified.

As suggested in another issue or PR, there should be a clearer distinction between sequence and field value list.
