### ISSUE TITLE
[protobuf.KafkaProtobufDeserializer Issue]: 

### ISSUE THREAD

**Issue by nrellanti** [corunet/kloadgen#262]
### What happened?

**when Enable**

1. Java Request: net.coru.kloadgen.sampler.KafkaSchemaSampler
2. Name: KLG - Value Schema File Deserialization Configuration
3. Deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
4. SchemaType: PROTOBUF

**Error message**
- Can't convert value of class com.google.protobuf.DynamicMessage to class net.coru.kloadgen.serializer.GenericAvroRecordSerializer specified in value.serializer

+++++++++++++++++++++++++++++++++++++++

**when Enable**

1. Java Request: net.coru.kloadgen.sampler.KafkaSchemaSampler
2. Name: KLG - Value Schema File Load Generator Config
3. Serializer: net.coru.kloadgen.serializer.ProtobufSerializer
4. SchemaType: PROTOBUF

**Error Message in the application server:**

- [WARN] [Camel (camel-1) thread #1 - KafkaConsumer[INCIDENTS-EVENTS]] [o.a.c.c.k.KafkaFetchRecords] [] : Exception org.apache.kafka.common.errors.RecordDeserializationException caught while polling INCIDENTS-EVENTS-Thread 0 from kafka topic INCIDENTS-EVENTS at offset {INCIDENTS-EVENTS/0=69154}: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 69. If needed, please seek past the record to continue consumption.

- [ERROR] [Camel (camel-1) thread #1 - KafkaConsumer[INCIDENTS-EVENTS]] [o.a.c.p.e.DefaultErrorHandler] [] : Failed delivery for (MessageId: 81BB4BE94B28CAE-0000000000000292 on ExchangeId: 81BB4BE94B28CAE-0000000000000292). Exhausted after delivery attempt: 1 caught: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 69. If needed, please seek past the record to continue consumption.. Processed by failure processor: FatalFallbackErrorHandler[Channel[DelegateSync[com.abc.enterpriselibraries.camel.prometheus.processor.FailureProcessor@5cff729b]]]
- [Messaging-Kafka-protobuf-test-deserializing.zip](https://github.com/corunet/kloadgen/files/8864345/Messaging-Kafka-protobuf-test-deserializing.zip)

### KloadGen Version

Kloadgen-4.7.0

### Relevant log output

```shell
1) Can't convert value of class com.google.protobuf.DynamicMessage to class net.coru.kloadgen.serializer.GenericAvroRecordSerializer specified in value.serializer

2) Topic: INCIDENTS-EVENTS, partition: 0, offset: 69
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by irodigl** [comment]
Hi @nrellanti,

Thank you for your collaboration, we will review the problem and we will inform you as soon as possible.

See ya!

**Comment by nrellanti** [comment]
Hi @irodigl,
I have tried KafkaSchemaSampler jmx file for producer alone and also tried for Producer and Consumer jmx file. In both cases I'm getting error messages in the final confluent control center/listener.

[Messaging-Kafka-protobuf-test-deserializing-producer-consumer-error-log.zip](https://github.com/corunet/kloadgen/files/8891818/Messaging-Kafka-protobuf-test-deserializing-producer-consumer-error-log.zip)
[Messaging-Kafka-protobuf-test-deserializing-updated-error-log.zip](https://github.com/corunet/kloadgen/files/8891819/Messaging-Kafka-protobuf-test-deserializing-updated-error-log.zip)

Please suggest!

**Comment by nrellanti** [comment]
Hello @irodigl ,

Here are the logs for Messaging-Kafka-protobuf-test-deserializing-producer-consumer.jmx

[WARN] [Camel (camel-1) thread #1 - KafkaConsumer[INCIDENTS-EVENTS]] [o.a.c.c.k.KafkaFetchRecords] [] : Exception org.apache.kafka.common.errors.RecordDeserializationException caught while polling INCIDENTS-EVENTS-Thread 0 from kafka topic INCIDENTS-EVENTS at offset {}: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 79734. If needed, please seek past the record to continue consumption.
Error

[ERROR] [Camel (camel-1) thread #1 - KafkaConsumer[INCIDENTS-EVENTS]] [o.a.c.p.e.DefaultErrorHandler] [] : Failed delivery for (MessageId: D2309F5C12E2579-000000000000002D on ExchangeId: D2309F5C12E2579-000000000000002D). Exhausted after delivery attempt: 1 caught: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 79734. If needed, please seek past the record to continue consumption.. Processed by failure processor: FatalFallbackErrorHandler[Channel[DelegateSync[com.jbhunt.enterpriselibraries.camel.prometheus.processor.FailureProcessor@6750e381]]]

Error
CDTorg.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 79734. If needed, please seek past the record to continue consumption. at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1429) at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:134) at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1652) at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1800(Fetcher.java:1488) at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:721) at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:672) at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1277) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211) at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:175) at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:97) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id -1 at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:174) at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:75) at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:27) at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60) at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1420) ... 15 common frames omitted Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte! at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.getByteBuffer(AbstractKafkaSchemaSerDe.java:250) at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:120) ... 19 common frames omitted

**Comment by jemacineiras** [comment]
Hi @nrellanti,

Thanks for the update. This error we already know, and we are working on it. But what we need is more log information for protobuf-test-deserializing-updated-error, since we are not able to see what was wrong there. In that case, you were using Confluence libraries, so they should work properly since they are "the official" ones. Can you increase the log level in this case, info or trace, just see what is going on?

Cheers

**Comment by irodigl** [comment]
Hi @nrellanti,

we have made the changes for fixing the bug and the code is available in this [branch](https://github.com/corunet/kloadgen/tree/%23262_kafka_protobuf_deserializer). Please could you testing it with both jmx solutions and using our Protobuf Serializer?

See ya!

**Comment by nrellanti** [comment]
Hello @irodigl , getting below errors in this [branch](https://github.com/corunet/kloadgen/tree/%23262_kafka_protobuf_deserializer).

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Malformed POM C:\Users\test\Desktop\kloadgen\pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<url>https://corunet.github.io/kloadgen/</url>\r\ns\r\n  <l... @15:5)  @ C:\Users\test\Desktop\kloadg
en\pom.xml, line 15, column 5
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project net.coru:kloadgen:4.8.2 (C:\Users\test\Desktop\kloadgen\pom.xml) has 1 error
[ERROR]     Malformed POM C:\Users\test\Desktop\kloadgen\pom.xml: expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<url>https://corunet.github.io/kloadgen/</url>\r\ns\r\n  <l... @15:5)  @ C:\Users\test\Desktop\kl
oadgen\pom.xml, line 15, column 5 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

**Comment by jemacineiras** [comment]
Hi @nrellanti,

there was a typo in the pom.xml. Sorry for that. Already fixed. Can you please try now?

Cheers!

**Comment by nrellanti** [comment]
Hi @irodigl , @jemacineiras,

Getting same errors, no change in the final messages. Please suggest!

Error
2022-06-15 17:23:20.140 CDT[2022-06-15 22:23:20,139] [WARN] [Camel (camel-1) thread #1 - KafkaConsumer[INCIDENTS-EVENTS]] [o.a.c.c.k.KafkaFetchRecords] [] : Exception org.apache.kafka.common.errors.RecordDeserializationException caught while polling INCIDENTS-EVENTS-Thread 0 from kafka topic INCIDENTS-EVENTS at offset {INCIDENTS-EVENTS/0=80288}: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 80289. If needed, please seek past the record to continue consumption.
Error
2022-06-15 17:23:20.141 CDT[2022-06-15 22:23:20,141] [ERROR] [Camel (camel-1) thread #1 - KafkaConsumer[INCIDENTS-EVENTS]] [o.a.c.p.e.DefaultErrorHandler] [] : Failed delivery for (MessageId: C054926BE813A6D-0000000000000148 on ExchangeId: C054926BE813A6D-0000000000000148). Exhausted after delivery attempt: 1 caught: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 80289. If needed, please seek past the record to continue consumption.. Processed by failure processor: FatalFallbackErrorHandler[Channel[DelegateSync[com.jbhunt.enterpriselibraries.camel.prometheus.processor.FailureProcessor@5d850a25]]]
Error
2022-06-15 17:23:20.141 CDTorg.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition INCIDENTS-EVENTS-0 at offset 80289. If needed, please seek past the record to continue consumption. at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1429) at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:134) at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1652) at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1800(Fetcher.java:1488) at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:721) at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:672) at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1304) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211) at org.apache.camel.component.kafka.KafkaFetchRecords.startPolling(KafkaFetchRecords.java:175) at org.apache.camel.component.kafka.KafkaFetchRecords.run(KafkaFetchRecords.java:97) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Protobuf schema for id 1 at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.toKafkaException(AbstractKafkaSchemaSerDe.java:259) at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:176) at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:75) at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:27) at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60) at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1420) ... 15 common frames omitted Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema 1 not found; error code: 40403 at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:297) at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:367) at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:836) at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:809) at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:277) at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaBySubjectAndId(CachedSchemaRegistryClient.java:409) at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:125) ... 19 common frames omitted
=======================
2022-06-16 15:20:42,500 ERROR n.c.k.s.KafkaConsumerSampler: Failed to receive message
org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition INCIDENTS-EVENTS-1 at offset 0. If needed, please seek past the record to continue consumption.
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1448) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:135) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1671) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1507) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:733) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:684) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1304) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1238) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211) ~[kloadgen-4.8.2.jar:?]
	at net.coru.kloadgen.sampler.KafkaConsumerSampler.runTest(KafkaConsumerSampler.java:104) [kloadgen-4.8.2.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id -1
	at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:174) ~[kloadgen-4.8.2.jar:?]
	at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:75) ~[kloadgen-4.8.2.jar:?]
	at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:27) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1439) ~[kloadgen-4.8.2.jar:?]
	... 15 more
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
	at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.getByteBuffer(AbstractKafkaSchemaSerDe.java:250) ~[kloadgen-4.8.2.jar:?]
	at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:120) ~[kloadgen-4.8.2.jar:?]
	at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:75) ~[kloadgen-4.8.2.jar:?]
	at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:27) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60) ~[kloadgen-4.8.2.jar:?]
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1439) ~[kloadgen-4.8.2.jar:?]
	... 15 more
2022-06-16 15:20:42,501 INFO o.a.j.t.JMeterThread: Thread is done: Consumer 2-1
2022-06-16 15:20:42,502 INFO o.a.j.t.JMeterThread: Thread finished: Consumer 2-1
2022-06-16 15:20:42,505 INFO o.a.j.t.JMeterThread: Thread is done: Producer 1-1
2022-06-16 15:20:42,505 INFO o.a.j.t.JMeterThread: Thread finished: Producer 1-1
2022-06-16 15:20:42,505 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2022-06-16 15:20:42,507 INFO o.a.k.c.c.i.ConsumerCoordinator: [Consumer clientId=consumer-anonymous-3, groupId=anonymous] Revoke previously assigned partitions INCIDENTS-EVENTS-1, INCIDENTS-EVENTS-0
2022-06-16 15:20:42,507 INFO o.a.k.c.c.i.ConsumerCoordinator: [Consumer clientId=consumer-anonymous-3, groupId=anonymous] Member consumer-anonymous-3-21dff046-052a-4f0b-8c00-224405a2705b sending LeaveGroup request to coordinator localhost:9092 (id: 2147483646 rack: null) due to the consumer is being closed
2022-06-16 15:20:42,508 INFO o.a.k.c.c.i.ConsumerCoordinator: [Consumer clientId=consumer-anonymous-3, groupId=anonymous] Resetting generation due to: consumer pro-actively leaving the group
2022-06-16 15:20:42,508 INFO o.a.k.c.c.i.ConsumerCoordinator: [Consumer clientId=consumer-anonymous-3, groupId=anonymous] Request joining group due to: consumer pro-actively leaving the group
2022-06-16 15:20:42,516 INFO o.a.k.c.m.Metrics: Metrics scheduler closed
2022-06-16 15:20:42,517 INFO o.a.k.c.m.Metrics: Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 15:20:42,517 INFO o.a.k.c.m.Metrics: Metrics reporters closed
2022-06-16 15:20:42,523 INFO o.a.k.c.u.AppInfoParser: App info kafka.consumer for consumer-anonymous-3 unregistered
2022-06-16 15:20:42,524 INFO o.a.k.c.p.KafkaProducer: [Producer clientId=] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2022-06-16 15:20:42,527 INFO o.a.k.c.m.Metrics: Metrics scheduler closed
2022-06-16 15:20:42,528 INFO o.a.k.c.m.Metrics: Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 15:20:42,528 INFO o.a.k.c.m.Metrics: Metrics reporters closed
2022-06-16 15:20:42,528 INFO o.a.k.c.u.AppInfoParser: App info kafka.producer for  unregistered
2022-06-16 15:20:42,529 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by jemacineiras** [comment]
Hi @nrellanti,

Those 2 errors mean different problems:
1. The client is not finding the Schema in the schema registry. My guessing is you are sending it using the File Component and that's the reason why is not found. When the File component is used, we add a fake version number (1) as you can see here
`15 common frames omitted Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema 1 not found; error code: 40403 at `

2. Looks like a problem with the serialization.
`Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!`

Are you using the solution in the branch provided by @irodigl ?
By the log you provided looks like is a JMeter test. You run the latest code as well here?

Cheers!!

**Comment by nrellanti** [comment]
Hi @jemacineiras,

I have tried by using KLG - Value Schema File Load Generator Config as well as KLG - Value Schema Load Generator Config. In both cases the error was same.

I have used new branch https://github.com/corunet/kloadgen/issues/262 and generated new jar file from this branch and executed load test from the JMeter.

**Comment by irodigl** [comment]
Hi @nrellanti,

I replicated carefully the test using the jmx producer/consumer from the beginning.

First at all, for use the confluent protobuf deserializer, you have to upload the schema in the schema registry. Are you writing correctly the name of the subject? Remember the protobuf specification for the name of the subject: "package name + message name".
`15 common frames omitted Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema 1 not found; error code: 40403 at` is related with this, so please check that the schema is in the registry schema and the name is exactly like the file you are uploading in Jmeter.

We used Postman for this case and the post was successfully:

![image](https://user-images.githubusercontent.com/104011351/174631131-b48e1719-8094-44d2-9b9d-0cc70f2ace43.png)

After that, in JMeter I execute the test plan and everything is all right:

![jmeter](https://user-images.githubusercontent.com/104011351/174631548-304f0251-c09f-4775-a3d6-02adbcb9b702.PNG)

We are not able to reproduce the error because in our environment everything is ok.

Please, let me note if the problem is due to the name of subject.

I hope I have been helpful!

**Comment by nrellanti** [comment]
Hi @irodigl, Thanks for your support and suggestions. You should close the bug.

**Comment by jemacineiras** [comment]
Hi @nrellanti,

Do you confirm is working for you after the advice from @irodigl?

Cheers
