### ISSUE TITLE
[Issue]: JavaClassCastException when working with logical types

### ISSUE THREAD

**Issue by Rivarsal** [corunet/kloadgen#289]
### What happened?

I got a JavaClassCastException when working with logical types:

![image](https://user-images.githubusercontent.com/59642284/185073629-a1e73190-d1a8-4a6e-98dc-763f9a7ef721.png)

### KloadGen Version

KloadGen 4.13.0

### Relevant log output

```shell
org.apache.kafka.common.errors.SerializationException: Can't convert value of class net.coru.kloadgen.serializer.EnrichedRecord to class net.coru.kloadgen.serializer.AvroSerializer specified in value.serializer
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:948) ~[kloadgen-4.13.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:905) ~[kloadgen-4.13.0.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:151) ~[kloadgen-4.13.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap') in field lastUpdateDate
	at org.apache.avro.generic.GenericDatumWriter.addClassCastMsg(GenericDatumWriter.java:191) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:229) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73) ~[kloadgen-4.13.0.jar:?]
	at net.coru.kloadgen.serializer.AvroSerializer.serialize(AvroSerializer.java:43) ~[kloadgen-4.13.0.jar:?]
	at net.coru.kloadgen.serializer.AvroSerializer.serialize(AvroSerializer.java:60) ~[kloadgen-4.13.0.jar:?]
	at net.coru.kloadgen.serializer.AvroSerializer.serialize(AvroSerializer.java:23) ~[kloadgen-4.13.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:945) ~[kloadgen-4.13.0.jar:?]
	... 8 more
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:160) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:81) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-4.13.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73) ~[kloadgen-4.13.0.jar:?]
	at net.coru.kloadgen.serializer.AvroSerializer.serialize(AvroSerializer.java:43) ~[kloadgen-4.13.0.jar:?]
	at net.coru.kloadgen.serializer.AvroSerializer.serialize(AvroSerializer.java:60) ~[kloadgen-4.13.0.jar:?]
	at net.coru.kloadgen.serializer.AvroSerializer.serialize(AvroSerializer.java:23) ~[kloadgen-4.13.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:945) ~[kloadgen-4.13.0.jar:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by Rivarsal** [comment]
Added Testplan and Avro

[BankAccountTestPlan.zip](https://github.com/corunet/kloadgen/files/9357903/BankAccountTestPlan.zip)
