### ISSUE TITLE
[Issue]: NullPointer when trying to send a Avro message

### ISSUE THREAD

**Issue by Perry45** [corunet/kloadgen#296]
### What happened?

Hello,

first thank you so much for implementing the possibility to send plain text. It is working for me!

But now with the new version (before I used 4.12.2) I get a NullPointer when I try to send a Avro message (see log). But the auto loading for nested elements is now working for me, which was not working before.

The Schema is:
`{
  "type": "record",
  "name": "MyFruitsValue",
  "namespace": "de.mycomp.avro.model",
  "doc": "schema",
  "fields": [
    {
      "name": "eventId",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      },
      "doc": "ID des gesendeten Events."
    },
    {
      "name": "otherId",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      },
      "doc": "id"
    },
    {
      "name": "somekey",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      },
      "doc": "someKey"
    },
    {
      "name": "aggregateId",
      "type": {
        "type": "record",
        "name": "AggregateId",
        "doc": "agg",
        "fields": [
          {
            "name": "ident",
            "type": {
              "type": "string",
              "avro.java.string": "String"
            },
            "doc": "ident"
          }
        ]
      },
      "doc": "agg"
    },
    {
      "name": "aggregateAttribute",
      "type": {
        "type": "record",
        "name": "AggregateAttribute",
        "doc": "agg",
        "fields": [
          {
            "name": "sequenceId",
            "type": {
              "type": "string",
              "avro.java.string": "String"
            }
          },
          {
            "name": "someReference",
            "type": [
              "null",
              {
                "type": "record",
                "name": "SomeReference",
                "fields": [
                  {
                    "name": "nabi",
                    "type": [
                      "null",
                      {
                        "type": "string",
                        "avro.java.string": "String"
                      }
                    ],
                    "default": null
                  },
                  {
                    "name": "curr",
                    "type": [
                      "null",
                      {
                        "type": "string",
                        "avro.java.string": "String"
                      }
                    ],
                    "default": null
                  }
                ]
              }
            ],
            "default": null
          },
          {
            "name": "someList",
            "type": [
              "null",
              {
                "type": "record",
                "name": "SomeList",
                "fields": [
                  {
                    "name": "fruits",
                    "type": [
                      "null",
                      {
                        "type": "array",
                        "items": {
                          "type": "record",
                          "name": "Fruit",
                          "fields": [
                            {
                              "name": "am",
                              "type": [
                                "null",
                                {
                                  "type": "record",
                                  "name": "Am",
                                  "fields": [
                                    {
                                      "name": "someCode",
                                      "type": [
                                        "null",
                                        {
                                          "type": "string",
                                          "avro.java.string": "String"
                                        }
                                      ],
                                      "default": null
                                    },
                                    {
                                      "name": "am",
                                      "type": [
                                        "null",
                                        {
                                          "type": "string",
                                          "avro.java.string": "String"
                                        }
                                      ],
                                      "default": null
                                    }
                                  ]
                                }
                              ],
                              "default": null
                            },
                            {
                              "name": "fruitType",
                              "type": [
                                "null",
                                {
                                  "type": "enum",
                                  "name": "FruitType",
                                  "symbols": [
                                    "APPLE",
                                    "BANANA"
                                  ]
                                }
                              ],
                              "default": null
                            },
                            {
                              "name": "referenceDate",
                              "type": [
                                "null",
                                {
                                  "type": "string",
                                  "avro.java.string": "String"
                                }
                              ],
                              "default": null
                            }
                          ]
                        }
                      }
                    ],
                    "default": null
                  }
                ]
              }
            ],
            "default": null
          },
          {
            "name": "error",
            "type": [
              "null",
              {
                "type": "record",
                "name": "Error",
                "fields": [
                  {
                    "name": "type",
                    "type": [
                      "null",
                      {
                        "type": "string",
                        "avro.java.string": "String"
                      }
                    ],
                    "default": null
                  },
                  {
                    "name": "title",
                    "type": [
                      "null",
                      {
                        "type": "string",
                        "avro.java.string": "String"
                      }
                    ],
                    "default": null
                  },
                  {
                    "name": "code",
                    "type": [
                      "null",
                      {
                        "type": "string",
                        "avro.java.string": "String"
                      }
                    ],
                    "default": null
                  },
                  {
                    "name": "detail",
                    "type": [
                      "null",
                      {
                        "type": "string",
                        "avro.java.string": "String"
                      }
                    ],
                    "default": null
                  }
                ]
              }
            ],
            "default": null
          },
          {
            "name": "otherMessageError",
            "type": [
              "null",
              {
                "type": "record",
                "name": "OtherMessageError",
                "fields": [
                  {
                    "name": "otherErrorList",
                    "type": [
                      "null",
                      {
                        "type": "array",
                        "items": {
                          "type": "record",
                          "name": "OtherError",
                          "fields": [
                            {
                              "name": "code",
                              "type": [
                                "null",
                                {
                                  "type": "string",
                                  "avro.java.string": "String"
                                }
                              ],
                              "default": null
                            },
                            {
                              "name": "message",
                              "type": [
                                "null",
                                {
                                  "type": "string",
                                  "avro.java.string": "String"
                                }
                              ],
                              "default": null
                            },
                            {
                              "name": "protocolType",
                              "type": [
                                "null",
                                {
                                  "type": "string",
                                  "avro.java.string": "String"
                                }
                              ],
                              "default": null
                            },
                            {
                              "name": "errorCategory",
                              "type": [
                                "null",
                                {
                                  "type": "string",
                                  "avro.java.string": "String"
                                }
                              ],
                              "default": null
                            }
                          ]
                        }
                      }
                    ],
                    "default": null
                  }
                ]
              }
            ],
            "default": null
          },
          {
            "name": "createdAt",
            "type": {
              "type": "string",
              "avro.java.string": "String"
            }
          }
        ]
      },
      "doc": "agg"
    }
  ]
}`

I tried several things. But what should work is just auto loading the fields and setting an arbitrary field length and it shouldn't result in a NullPointer right?

Before with the old version I did something like:
aggregateAttribute.error | null | 0 | []
aggregateAttribute.otherMessageError | null | 0 | []
if I do not need the (nested) error objects, this should work as well right? (it did before) 

If you need further information pls tell me. To provide a JMX Testplan would be work intensive so maybe you could check it without it?

### KloadGen Version

5.1.0

### Relevant log output

```shell
java.lang.NullPointerException: null
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:196) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:216) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:208) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:212) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:216) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:208) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:216) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:208) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:208) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.isOptionalFieldAccordingToSchema(AvroObjectCreatorFactory.java:156) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.SchemaProcessor.shouldProcessAccordingToSubField(SchemaProcessor.java:185) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.SchemaProcessor.shouldProcessField(SchemaProcessor.java:175) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.SchemaProcessor.lambda$calculateFieldsToProcess$0(SchemaProcessor.java:164) ~[kloadgen-5.1.0.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.ArrayDeque$DeqSpliterator.forEachRemaining(ArrayDeque.java:849) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at net.coru.kloadgen.processor.SchemaProcessor.calculateFieldsToProcess(SchemaProcessor.java:165) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.processor.SchemaProcessor.next(SchemaProcessor.java:38) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroSRLoadGenerator.nextMessage(AvroSRLoadGenerator.java:50) ~[kloadgen-5.1.0.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:129) ~[kloadgen-5.1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by dianaGomezGar** [comment]
Hi @Perry45,

Thank you for notifying this error. You should add a valid JMX file, anyway, we are going to try to replicate it without a specific JMX test plan. If we finally need it, we ask you for it.  

We will let you know about our progress with this issue as soon as possible.

**Comment by mortizam** [comment]
Good afternoon, @Perry45.

We have tried to solve the error you awared us about. The changes are not in master branch yet, but they are in the linked branch to this issue ([296-issue-nullpointer-when-trying-to-send-a-avro-message](https://github.com/corunet/kloadgen/tree/296-issue-nullpointer-when-trying-to-send-a-avro-message)).

Can you check if the problem is solved before we open the PR, please?

Greetings and thanks.

**Comment by Perry45** [comment]
Yeah, sorry for not providing the jmx, but I'm on holiday next week. I'll provide it the week after.

I tried 5.1.1 based on 296 and now I get:

`org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:154) ~[kloadgen-5.1.1.jar:?]
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:61) ~[kloadgen-5.1.1.jar:?]
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62) ~[kloadgen-5.1.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:945) ~[kloadgen-5.1.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:905) ~[kloadgen-5.1.1.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:141) ~[kloadgen-5.1.1.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException: null of de.mycomp.avro.model.FruitType of union in field fruitType of de.mycomp.avro.model.Fruit of array of union in field fruits of de.mycomp.avro.model.FruitList of union in field fruitList of de.mycomp.avro.model.AggregateAttribute in field aggregateAttribute of de.mycomp.avro.model.MyFruitsValue
	at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:184) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:178) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73) ~[kloadgen-5.1.1.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.writeDatum(AbstractKafkaAvroSerializer.java:168) ~[kloadgen-5.1.1.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:146) ~[kloadgen-5.1.1.jar:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at org.apache.avro.Schema$EnumSchema.getEnumOrdinal(Schema.java:1060) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeEnum(GenericDatumWriter.java:242) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:134) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:145) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:257) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:137) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:145) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:145) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83) ~[kloadgen-5.1.1.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73) ~[kloadgen-5.1.1.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.writeDatum(AbstractKafkaAvroSerializer.java:168) ~[kloadgen-5.1.1.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:146) ~[kloadgen-5.1.1.jar:?]
	... 11 more
`

Seems to be very similar now to the error I already reported: https://github.com/corunet/kloadgen/issues/279
