### ISSUE TITLE
[Issue]: Nullpointer at ValueReplacer

### ISSUE THREAD

**Issue by fabianAtruvia** [corunet/kloadgen#301]
## Expect
Sending Kafka messages with a key that uses a changing UUID.
- The function `${__UUID()}` of [JMeter](https://jmeter.apache.org/usermanual/functions.html#__UUID) is to be used for this. 
- Variables `${TEST_VAR}` can also not be used as an alternative.
- ![Nullpointer jmx](https://user-images.githubusercontent.com/114665063/193031784-700b774e-ca0c-4cd8-949b-e1e7374aaff6.png)

## Result
A NullPointerException always occur in this case.

## More information
KloadGen: 5.1.1
JMeter: 5.5
Schema: Is not required
Testplan: [Nullpointer.zip](https://github.com/corunet/kloadgen/files/9674424/Nullpointer.zip) (Minimal test plan. A running Kafka is not required to produce the NullPointerException)

### KloadGen Version

5.1.1

### Relevant log output

```shell
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: About to replace in property of type: class org.apache.jmeter.testelement.property.StringProperty: KLG - Value Plain - VARIABLE - ❌
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: Replacement result: KLG - Value Plain - VARIABLE - ❌
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: About to replace in property of type: class org.apache.jmeter.testelement.property.BooleanProperty: true
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: Won't replace true
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: About to replace in property of type: class org.apache.jmeter.testelement.property.StringProperty: ${TEST_VAR}
2022-09-29 13:59:35,202 DEBUG o.a.j.t.p.AbstractProperty: Not running version, return raw function string
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: Replacement result: ${TEST_VAR}
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: About to replace in property of type: class org.apache.jmeter.testelement.property.StringProperty: org.apache.kafka.common.serialization.StringSerializer
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: Replacement result: org.apache.kafka.common.serialization.StringSerializer
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: About to replace in property of type: class org.apache.jmeter.testelement.property.StringProperty: 
2022-09-29 13:59:35,202 DEBUG o.a.j.e.u.ValueReplacer: Replacement result: 
2022-09-29 13:59:35,202 DEBUG o.a.j.t.p.AbstractProperty: Not running version, return raw function string
2022-09-29 13:59:35,202 DEBUG o.a.j.t.p.AbstractProperty: Not running version, return raw function string
2022-09-29 13:59:35,202 DEBUG o.a.j.p.j.s.JavaSampler: StandardJMeterEngine@6ec2ddb3-Java Request	testStarted
2022-09-29 13:59:35,202 INFO o.a.j.p.j.s.JavaSampler: Created class: net.coru.kloadgen.sampler.KafkaSchemaSampler. Uses tearDownTest: 
2022-09-29 13:59:35,203 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2022-09-29 13:59:35,203 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,6,main]
java.lang.NullPointerException: null
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:994) ~[jorphan.jar:5.5]
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:994) ~[jorphan.jar:5.5]
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:976) ~[jorphan.jar:5.5]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:405) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by dianaGomezGar** [comment]
Hi @fabianAtruvia ,

Thank you for your report. We already know about this error and we are working to fix it. We let you know as soon as we have a solution.

**Comment by dianaGomezGar** [comment]
This is the related issue to implement this functionality:
https://github.com/corunet/kloadgen/issues/298

**Comment by jemacineiras** [comment]
Hi @fabianAtruvia,

there is a PR which will solve this issue. You can test it before merge if you like.

Cheers!

**Comment by fabianAtruvia** [comment]
**Thank you @jemacineiras. The generation of the UUID is now possible. 😀👍**

Unfortunately, the UUID is only generated once per thread and not per message.
Is this a problem of the plugin, JMeter or the user?

![UUID Function](https://user-images.githubusercontent.com/114665063/196400883-e5e38a86-4a94-4e3e-9a9a-85d5b2e08b8d.png)

![UUID](https://user-images.githubusercontent.com/114665063/196400924-53976ec0-e6b4-4537-b51e-975e070f7b29.png)
![UUID via Thread](https://user-images.githubusercontent.com/114665063/196400918-03f576df-a4df-4002-a970-b9d9df67354e.png)

**Comment by dianaGomezGar** [comment]
Hi @fabianAtruvia, 
I'll check it out and tell you something as soon as I can.

**Comment by dianaGomezGar** [comment]
Hi @fabianAtruvia, 

Actually, we generate values from the data that Jmeter give us, so maybe the problem is that you are generating only one thread with 10 loops, so it's possible that Jmeter generate only 1 uuid because it's only one thread. 
Could you try to generate data changing the values number of threads instead of loops (10 threads, 1 loop)? 

If that doesn't work, I need the .Jmx that fails, the data and the schema you are using to replicate this behaviour and locate better what kind of error is.

**Comment by fabianAtruvia** [comment]
Hi @dianaGomezGar 
yes, you are right. There is only one UUID created per thread. Seems to be the same "problem" as here: https://stackoverflow.com/questions/32120921/different-values-for-jmeter-uuid-in-loop
Therefore, I think it is a general problem/feature of JMeter.

Thus, the bow can be closed.

Greatings Fabian

**Comment by fabianAtruvia** [comment]
With a `PreProcessor` it is working
Define a variable: `vars.put("myUUID",UUID.randomUUID().toString());`
![grafik](https://user-images.githubusercontent.com/114665063/196615196-5fc43105-85aa-4199-99bd-551e3d64d514.png)

Use it in `KLG - Key Plain Load Generator Config`
![grafik](https://user-images.githubusercontent.com/114665063/196615377-ab9a1a8f-2fb0-41a6-8b1a-ade1c97f147f.png)
