### ISSUE TITLE
[Issue]:  Not able to run test example on JMeter (NPE & Class Not Found Exceptions)

### ISSUE THREAD

**Issue by alchemistsrivastava** [corunet/kloadgen#304]
### What happened?

Cannot load example in from the JMeter UI
1.  Build Kloadgen JAR
2. Added JAR in the JMeter lib ext folder
3. Started JMeter
4. Imported Kloadgen example (apache-jmeter-5.5/Example-Test-Plan.jmx)
5. Getting  exception 

Also when I try to run following command getting NPE
java -jar target/standalone.jar -h "/jmeter/apache-jmeter-5.5" 2 -l testlogs/result.log -t Example-Test-Plan.jmx -r testlogs

NFO: Running test (1665806605539)
Exception in thread "main" java.lang.NullPointerException
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:994)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:994)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:976)
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:391)
	at net.coru.kloadgen.KLoadGenStandalone.main(KLoadGenStandalone.java:93)
Oct 14, 2022 9:03:25 PM org.apache.jmeter.reporters.ResultCollector$ShutdownHook run
INFO: Shutdown hook started

### KloadGen Version

kloadgen-5.1.1.jar

### Relevant log output

```shell
2022-10-14 20:59:19,560 INFO o.a.j.s.FileServer: Default base='/jmeter/apache-jmeter-5.5/bin'
2022-10-14 20:59:19,563 INFO o.a.j.g.a.Load: Loading file: //jmeter/apache-jmeter-5.5/Example-Test-Plan.jmx
2022-10-14 20:59:19,563 INFO o.a.j.s.FileServer: Set new base='//jmeter/apache-jmeter-5.5'
2022-10-14 20:59:19,644 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2022-10-14 20:59:19,653 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2022-10-14 20:59:19,654 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2022-10-14 20:59:19,655 INFO o.a.j.s.SaveService: Loading file: /jmeter/apache-jmeter-5.5/Example-Test-Plan.jmx
2022-10-14 20:59:19,789 WARN o.a.j.g.a.Load: Missing jar file. java.lang.NoClassDefFoundError: org/reflections/Configuration
java.lang.NoClassDefFoundError: org/reflections/Configuration
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3138) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3343) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2554) ~[?:?]
	at org.apache.jmeter.testbeans.gui.GenericTestBeanCustomizer.<init>(GenericTestBeanCustomizer.java:247) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.testbeans.gui.TestBeanGUI.init(TestBeanGUI.java:425) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.testbeans.gui.TestBeanGUI.configure(TestBeanGUI.java:301) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addComponent(JMeterTreeModel.java:162) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:131) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:131) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:123) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.GuiPackage.addSubTree(GuiPackage.java:554) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.Load.insertLoadedTree(Load.java:199) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:130) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.Load.doActionAfterCheck(Load.java:88) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.5]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.reflections.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 32 more
2022-10-14 20:59:19,795 ERROR o.a.j.u.JMeterUtils: org/reflections/Configuratio
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by alchemistsrivastava** [comment]
I am just trying to understand how to test the sample.    These steps mentioned in the doc did not work for me.
1. Build Kloadgen JAR from git repo
2. Added JAR in the JMeter lib ext folder (**Getting Kafka exceptions do we need to add Kafka JARs also?**)
3. Started JMeter
4. Imported sample Kloadgen example (apache-jmeter-5.5/Example-Test-Plan.jmx).  But getting error mentioned above.
5. Trying to start Kloadgen using this command got NPE (java -jar target/standalone.jar -h "/jmeter/apache-jmeter-5.5" 2 -l testlogs/result.log -t Example-Test-Plan.jmx -r testlogs)

**Comment by jemacineiras** [comment]
Hi @alchemistsrivastava,

you are building the standalone profile, right?
I'll check and will back to you.

Thanks!

**Comment by jemacineiras** [comment]
Hi @alchemistsrivastava,

I found this is a "new issue" we are solving in this [branch](https://github.com/corunet/kloadgen/tree/301-issue-nullpointer-at-valuereplacer) can you please test it if it work for you?
cheers

**Comment by alchemistsrivastava** [comment]
Thanks @jemacineiras I will test and update soon.

**Comment by alchemistsrivastava** [comment]
Thanks @jemacineiras 

Getting this error now:
2022-10-17 06:16:54,143 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1156) ~[jackson-core-2.13.3.jar:2.13.3]
	at org.apache.avro.Schema$Parser.parse(Schema.java:1421) ~[standalone.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroSRLoadGenerator.setUpGenerator(AvroSRLoadGenerator.java:46) ~[standalone.jar:?]
	at net.coru.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:357) ~[standalone.jar:?]
	at net.coru.kloadgen.sampler.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:63) ~[standalone.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.5.1-SNAPSHOT]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5.1-SNAPSHOT]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5.1-SNAPSHOT]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5.1-SNAPSHOT]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:830) ~[?:?]

**Comment by alchemistsrivastava** [comment]
I am just trying to test the example code.

**Comment by jemacineiras** [comment]
Hi @alchemistsrivastava,

my guessing is you have not uploaded the schema files provided as example into de Schema Registry, did you?

Otherwise, can you provide exactly the steps you are following to run the tests?

Cheers!!!

**Comment by jemacineiras** [comment]
Hi @alchemistsrivastava,

any luck with this? Did you have a chance to try what I recommend in the previous answer?

Cheers

**Comment by dianaGomezGar** [comment]
I'm going to close due to inactivity. If you have any question you can open a new Issue or reopen this one.
