### ISSUE TITLE
404 Error trying to get Schema with Value Schema Serializer Config

### ISSUE THREAD

**Issue by jorge-dutton** [corunet/kloadgen#312]
### What happened?

Hello, 

My environment is:
Confluent Platform 7.3.0
Java 11
Kloadgen 5.1.3
JMeter 5.5
SO: Mac OS

The steps are these:
1. I set up the Schema Registry Config Element for my local Confluent at port 8081 and the result is ok
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/6779721/203771917-07e84cfb-47dc-4678-974d-f709b61d8de0.png">
2. When I try to setup the Value Schema Serializer Config, I get an HTTP 404 error trying to retrieve the schema properties:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/6779721/203772366-76a4238e-82af-4d25-832e-2a9e0df1a82e.png">

3. I moved to use the Value Schema Serializer Config, setting the avsc, but in this case the problem is that, when the fields are of string type and I set a value list, the values are not passed and the topic receives null. This works perfectly for fields of type long or int. Yo can see the example for the TRANSACTION_ID value
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/6779721/203773902-07b4a4f0-0b0b-4061-9ae2-c0742fc327db.png">

[ThreadGroup-Barcodes_Dufry_v1.jmx.zip](https://github.com/corunet/kloadgen/files/10084090/ThreadGroup-Barcodes_Dufry_v1.jmx.zip)
[avro-schemas.zip](https://github.com/corunet/kloadgen/files/10084150/avro-schemas.zip)

### KloadGen Version

KloadGen 5.1.3

### Relevant log output

```shell
-----
This is the log error when trying to set string values to the Value Schema File Serializer Config
---
2022-11-24 12:37:10,440 WARN o.a.k.c.u.AppInfoParser: Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436) ~[?:?]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1862) ~[?:?]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:957) ~[?:?]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:892) ~[?:?]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:317) ~[?:?]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:523) ~[?:?]
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64) ~[kloadgen-5.1.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:436) ~[kloadgen-5.1.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:292) ~[kloadgen-5.1.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:319) ~[kloadgen-5.1.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:304) ~[kloadgen-5.1.3.jar:?]
	at net.coru.kloadgen.sampler.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:83) ~[kloadgen-5.1.3.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by davidgarciago** [comment]
Hi @jorge-dutton,
Thank you for your collaboration. We are working into it and will get back to you as soon as possible.

**Comment by davidgarciago** [comment]
Hi again @jorge-dutton 
Currently config elements "Schema Registry Config Element" and "Value Schema Serializer Config" depend on each other and its not possible to have the Schema Registry Config outside the thread group because KLoadGen does not support that function yet. Please move that configuration element inside each thread group and try again to check that the problem is solved.

In the case of "Value Schema File Serializer Config" you are using the confluent kafka serializer instead of the one from KLoadGen. This Serializer uses your namespace to search for the schema in the schema registry so the name of the subject or the namespace of the avro file should be changed in order to be found by KloadGen.

I hope i helped to solve your problem, please let me know!

**Comment by jorge-dutton** [comment]
Hi @davidgarciago 

Thank you, I moved the Schema Reg. Config into the Thread Group and it works with the Value Schema Serializer Config. 

I didn't manage to produce records with the Value Schema File Serializer Config and the Kaloadgen serializers, they have problems to map one field of type log_timestamp-millis and I keep on getting ClassCastException.

I Close the issue, because I can keep on using the first Value Schema Serializer.

**Comment by davidgarciago** [comment]
Hi @jorge-dutton,

I'm opening a new issue regarding that specific problem. If I have any news i will let you know.

Thank you again for your collaboration!
