### ISSUE TITLE
Kafka Headers not sending any headers

### ISSUE THREAD

**Issue by JozefTomko** [corunet/kloadgen#45]
Hi
I'm having an issue with Kafka Headers Configuration.
It doesn't send any headers in the producer.
I tried sending custom string as well as headers from example test plan.
![Kafka_Header](https://user-images.githubusercontent.com/26792025/87397162-28f2b000-c5b4-11ea-877f-3a34bb0e6694.png)

**Comment by kszosze** [comment]
Hi Jozef,
headers are sent, but they are not added to the Sampler Object, which is the one you are reading there.

I´ll create a branch to add them since you request it.
Cheers!!

**Comment by kszosze** [comment]
Hi @JozefTomko 
There is a branh + PR with the changes I made after your request. Do you mind test it if it solve your problem?

Regards

**Comment by JozefTomko** [comment]
Hi @kszosze 
Thanks for your quick response.
From the new branch, there is some issue with Kafka producer properties. Both schema registry and specific schema retrieve successfully, but fails producing kafka.

Error:
```
2020-07-17 10:32:01,483 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:457) ~[kafka-clients-2.0.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:304) ~[kafka-clients-2.0.0.jar:?]
	at net.coru.kloadgen.sampler.ConfluentKafkaSampler.setupTest(ConfluentKafkaSampler.java:238) ~[kloadgen-2.0.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:195) ~[ApacheJMeter_java.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: io.confluent.common.config.ConfigException: Missing required configuration "schema.registry.url" which has no default value.
	at io.confluent.common.config.ConfigDef.parse(ConfigDef.java:251) ~[kloadgen-plugin-2.0.0.jar:?]
	at io.confluent.common.config.AbstractConfig.<init>(AbstractConfig.java:78) ~[kloadgen-plugin-2.0.0.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig.<init>(AbstractKafkaAvroSerDeConfig.java:136) ~[kloadgen-plugin-2.0.0.jar:?]
	at io.confluent.kafka.serializers.KafkaAvroSerializerConfig.<init>(KafkaAvroSerializerConfig.java:32) ~[kloadgen-plugin-2.0.0.jar:?]
	at io.confluent.kafka.serializers.KafkaAvroSerializer.configure(KafkaAvroSerializer.java:48) ~[kloadgen-plugin-2.0.0.jar:?]
	at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.configure(ExtendedSerializer.java:60) ~[kafka-clients-2.0.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:364) ~[kafka-clients-2.0.0.jar:?]
	... 8 more

```

**Comment by kszosze** [comment]
HI @JozefTomko 
weird, I tested yesterday before commit the branch. 
Can you describe how are you performing the test?
Using the guy, standalone....
Cheers

**Comment by JozefTomko** [comment]
Hi @kszosze 
I build the project using  "mvn clean install -P standalone". 
After adding kloadgen-plugin-2.0.0.jar file to lib/ext I run Jmeter in GUI and create new project, add each Kafka config element, 
configure connection to schema registry successfully, download specific schema and using ConfluentKafkaSampler java request try to generate kafka message.
There is no issue with issue with the current master version, except the header.

**Comment by kszosze** [comment]
Hi @JozefTomko,

Problem had been fixed. Can you try that branch?
Cheers!!

**Comment by kszosze** [comment]
Hi @JozefTomko,

any joy with that?

Cheers!

**Comment by JozefTomko** [comment]
Hi @kszosze 
Sorry for the slow response.
Branch works great, issue is fixed. Thanks for fast resolve.
