### ISSUE TITLE
NoClassDefFoundError when using kloadgen-plugin-2.1.3.jar in JMeter 5.1.1

### ISSUE THREAD

**Issue by saddaguduru** [corunet/kloadgen#66]
[pom.zip](https://github.com/corunet/kloadgen/files/5520619/pom.zip)

Getting below error even though I don't have "log4j-slf4j-impl-2.11.1.jar" in JMeter/lib folder. Attached the pom.xml that I used to build the kloadgen-plugin-2.1.3.jar.

C:\gitRepos\jmeter-5.1.1\bin>jmeter.bat
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/gitRepos/jmeter-5.1.1/lib/log4j-slf4j-impl-2.11.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/gitRepos/jmeter-5.1.1/lib/ext/kloadgen-plugin-2.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil
        at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:78)
        at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:60)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at org.apache.jmeter.JMeter.<clinit>(JMeter.java:124)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.jmeter.NewDriver.main(NewDriver.java:251)

**Comment by saddaguduru** [comment]
Thanks for the comment. I did not create any JMeter test plan. I got the error when launching the JMeter tool after copying the kloadgen-plugin-2.1.3.jar under my JMeter-5.1.1\lib\ext folder and JMeter is not starting up.

**Comment by kszosze** [comment]
HI @saddaguduru ,
we support jmeter from version 5.2.1 and 5.3 over java 8+. You can modify the POM to remove the org.apache.logging.log4j dependencies which cause the problem but later on you will face other funny issues due the dependencies we package in the jar. 
My advice is you upgrade later JMeter versions.
Regards.

**Comment by saddaguduru** [comment]
Thanks @kszosze for the info. I will upgrade my JMeter and try again.

**Comment by kszosze** [comment]
HI @saddaguduru ,
any luck with the upgrade?
Cheers

**Comment by codigoFuentes** [comment]
Closed by inactivity
