### ISSUE TITLE
Getting exception when using the Example-Test-Plan.jmx

### ISSUE THREAD

**Issue by harold-kfuse** [corunet/kloadgen#86]
I'm trying to test Kloadgen. I built the standalone jar from master branch and use the included Example-Test-Plan.jmx. I only updated the bootstrap.servers and kafka.topic.name in this jmx file. When I try to run it, I'm getting the following exception:

Exception in thread "Thread Group 1-1" java.lang.Error: This should never happen. Tried to invoke:
net.coru.kloadgen.config.valueserialized.ValueSerializedConfigElement#setValueSchemaProperties(String  )
	at org.apache.jmeter.testbeans.TestBeanHelper.invokeOrBailOut(TestBeanHelper.java:168)
	at org.apache.jmeter.testbeans.TestBeanHelper.prepare(TestBeanHelper.java:96)
	at org.apache.jmeter.threads.TestCompiler.trackIterationListeners(TestCompiler.java:182)
	at org.apache.jmeter.threads.TestCompiler.subtractNode(TestCompiler.java:136)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:997)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:994)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:976)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:704)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:252)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.jmeter.testbeans.TestBeanHelper.invokeOrBailOut(TestBeanHelper.java:166)
	... 9 more

Is there anything else I need to update in the jmx file to use it?

**Comment by codigoFuentes** [comment]
Hi  harold-kfuse.
Do you want to use the plugin as a Jmeter library or as a standalone jar?

**Comment by harold-kfuse** [comment]
I am trying to use the standalone jar to generate load to kafka.

**Comment by kszosze** [comment]
Hi @harold-kfuse,
we are gonna take a look into it and back to you as soon as possible. I guess you are using the latest master, right?

**Comment by harold-kfuse** [comment]
Correct. I'm using the latest master.

**Comment by kszosze** [comment]
I see, test plans are not fully updated. After latest changes we did not create new test plans. I will update then and push them. After that it should work. Keep in mind, some of the test plans require to populate schemas in the schema registry. I also will provide the necessary avsc files for that.
Cheers

**Comment by kszosze** [comment]
HI @harold-kfuse,
I´ve prepared a branch with the fixed test plans and some other changes. Keep in mind that in order to use the Example-Test-Plan you need to inject the schema into the schema registry. Needed files are provided in the schema_registry_docker folder.

**Comment by harold-kfuse** [comment]
Thanks! Is there also an example test plan if we just want to send a json message?

**Comment by kszosze** [comment]
HI @harold-kfuse,
It will depend of your use case, we actually support JSON-Schema definitions. But if you want to send a plain JSON, that is not supported by this plugin, for now.
Cheers!

**Comment by kszosze** [comment]
Close after issue resolution
